name: TerraTest Pipeline

trigger: none
# - main
pool: New_agent

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd .\terratest\
      go mod init "vnettest"
      go mod tidy
      go get github.com/gruntwork-io/terratest
      go mod tidy
      go test -v -timeout 30m
    workingDirectory: '$(System.DefaultWorkingDirectory)'
