name: TerraTest Pipeline

trigger: none
# - main
pool: Agent_01_Dec2025

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd $(System.DefaultWorkingDirectory)\terratest\
      go mod init "vnettest"
      go mod tidy
      go get github.com/gruntwork-io/terratest
      go mod tidy
      go test -v -timeout 30m
    workingDirectory: '$(System.DefaultWorkingDirectory)'


